### ISSUE TITLE
[QUESTION] Can this also UPDATE your 3DS?

### ISSUE THREAD

**Issue by ghost** [Plailect/sysDowngrader#33]
Hello, I am on an Old 3DS XL, but I don't want to update to 11.3 as I know it's a problem for some homebrew and A9LH users. I have a 10.3 update pack. Can I update my 3DS with it? Sorry for being a noob.

**Comment by HugaShire** [comment]
Yes it can.

**Comment by Plailect** [comment]
It only has hashes for specific versions.

**Comment by MelonGx** [comment]
Well it may wipe out A9LH if trying to upgrade SysNAND with this software.
For special consoles like 初階版 (Beginner Edition) which have to upgrade firmware by installing CIA to "unlock" something, use this software to upgrade EmuNAND instead of SysNAND then write upgraded EmuNAND back to SysNAND in order to avoid wiping out A9LH.
